language: c 

before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
  - mozroots --import --sync
  - sudo chmod 755 src/.nuget/NuGet.exe

env:
  - EnableNuGetPackageRestore=true

script:
  - xbuild src/NuGet.PacMan.sln